// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfkrnlumnvzurfffebbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRma3JubHVtbnZ6dXJmZmZlYmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTI3MTMsImV4cCI6MjA2MDAyODcxM30.3bbNBI2-JwWwRq52ovsSWYqH794yev8yK-R_yOMRcjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);